<a href="https://colab.research.google.com/github/Asifbinsyed/Pytorch/blob/main/tensors_campusX.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

if torch.cuda.is_available():
  print(f"the cuda is available")
  print(f"the available device is {torch.cuda.get_device_name(0)}")
else:
  print(f'GPU is not available.')

GPU is not available.


In [6]:
torch.__version__

'2.5.1+cu121'

In [8]:
# Creating the tensor
torch.empty(2,3)

tensor([[8.3195e+35, 2.1708e-18, 1.2059e+27],
        [3.0951e-18, 9.8686e+17,        nan]])

In [12]:
# Creating Zeroes
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
# Creating ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [16]:
# Creating Random Values
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

# Tensor Shapes

In [20]:
a= torch.tensor([[1,2,3], [2,3,4]])
a.shape

torch.Size([2, 3])

In [24]:
torch.empty_like(a)

tensor([[    135284008828304,     135284008828304,                   0],
        [                  0,      97362613633024, 7310593858020254331]])

In [25]:
torch.zeros_like(a)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [26]:
torch.ones_like(a)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [36]:
torch.rand_like(a, dtype= torch.float32)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

# Data Type

In [30]:
a.dtype

torch.int64

In [32]:
# for example we have to create a data type at the time of creating the tensor

a = torch.tensor([[2,3,4], [2,3,4]], dtype= torch.int32)


In [35]:
# you can also change the data type for a tensor
a.to(torch.float32)


tensor([[2., 3., 4.],
        [2., 3., 4.]])

In [45]:
# different type of operation with tensor
b= torch.rand(2,2).to(torch.float32)
c = torch.rand(2,2).to(torch.float32)
# addition
b + c

# subtraction
b- c

# multilplication
b * c

# Division

b/c

# integer division

(b * 100/ c)//2

# mod

((b * 100/ c)//2)%2

# power

b ** 2


tensor([[9.6261e-01, 7.6321e-03],
        [1.6499e-05, 1.1841e-02]])

# Basif operation

In [59]:
a= torch.tensor([1.5,-2,3,4])

# abs
torch.abs(a)

#  round
torch.round(a)

# negetive
torch.neg(a)

# Ceill
torch.ceil(a)

# torch floor

torch.floor(a)

# Clamp

torch.clamp(a, min= 2, max= 3 )

tensor([2., 2., 3., 3.])

# Reduction operation

In [68]:
# creating the random torch

a = torch.rand(2,3)
b = torch.rand(2,3)

# sum
a.sum()

# sum along the column

a.sum(dim=0)

# Sum along the rows

a.sum(dim= 1)

# same goes for max, min, product, standard deviation, variance

# argmax

a.argmax()

# argmin
a.argmin()

tensor(5)

# Matrix operation

In [19]:
a = torch.randint(1,9, (2,2))
b = torch.randint(1,9, (2,2))



In [20]:
# matrix multiplication
torch.matmul(a,b)

tensor([[53, 71],
        [31, 45]])

In [22]:
# vector dot product
t1, t2 = torch.tensor([0, 1]), torch.tensor([2, 3])
torch.dot(t1,t2)

tensor(3)

In [25]:
# Matrix transpose
torch.transpose(a, 0,1)

tensor([[7, 5],
        [3, 1]])

In [27]:
# determinant of matrix
a = torch.randint(1,9, (2,2)).to(torch.float32)
torch.det(a)

tensor(3.)

In [28]:
# inverse matrix
torch.inverse(a)

tensor([[ 1.0000, -1.0000],
        [-0.3333,  0.6667]])

# Comparison funciton in torch

In [41]:
# create the tensor

a = torch.randint(size=(2,3), low= 0 , high = 10).to(torch.float32)
b = torch.randint(size = (2,3), low= 0 , high = 10)



In [35]:
# compare each of the item
a>b

tensor([[False, False, False],
        [ True,  True, False]])

# Special Function

In [36]:
torch.sigmoid(a)

tensor([[0.9526, 0.7311, 0.8808],
        [0.9997, 0.9933, 0.5000]])

In [42]:
torch.softmax(a,1)

tensor([[7.2748e-01, 2.6762e-01, 4.9017e-03],
        [9.0496e-04, 6.6868e-03, 9.9241e-01]])

In [43]:
torch.relu(a)

tensor([[8., 7., 3.],
        [2., 4., 9.]])

# Inplace operation

In [45]:
# we just have to add an underscore

a.add_(b)

tensor([[14., 13.,  6.],
        [10.,  8., 17.]])

In [46]:
a.relu_()

tensor([[14., 13.,  6.],
        [10.,  8., 17.]])

# Clone

In [47]:
c=a.clone()

# Cuda variable

In [7]:
# create a cuda variable
import torch
a = torch.randint(2,9,(4,4)).to(device= "cuda")

In [8]:
torch.reshape(a,(2,2,2,2))

tensor([[[[7, 2],
          [6, 6]],

         [[7, 2],
          [8, 6]]],


        [[[5, 3],
          [4, 8]],

         [[7, 3],
          [6, 8]]]], device='cuda:0')

In [9]:
# flattening : it is basically you can make it one dimensional array:

torch.flatten(a)

tensor([7, 2, 6, 6, 7, 2, 8, 6, 5, 3, 4, 8, 7, 3, 6, 8], device='cuda:0')

# Permutation

Suppose you have created a tensor of (2,3,4) shape. but now you want to change the shape size in a way that the size in the number is just different. In that case you just use permute

In [10]:
x = torch.rand(2,3,4)
print(x.shape)

y= torch.permute(x,(2,0,1))
print(y.shape)


torch.Size([2, 3, 4])
torch.Size([4, 2, 3])


# Squeeze and Unsqueeze

Squeeze and Unsqueeze are function to either chip in a new dimension or remove a dimension from a tensor. use case could be when we
use batch processing so in that case we chip in a new dimension

In [14]:
torch.unsqueeze(x,0).shape

torch.Size([1, 2, 3, 4])

In [24]:
a=torch.squeeze(y,1)

In [25]:
a.shape

torch.Size([4, 2, 3])

In [28]:
torch.squeeze(a,dim=1).shape

torch.Size([4, 2, 3])

In [29]:
import torch

# Create a tensor with an extra dimension
tensor_with_extra_dim = torch.randint(0, 10, (1, 3, 1, 4))
print("Original tensor shape:", tensor_with_extra_dim.shape)  # Output: torch.Size([1, 3, 1, 4])

# Squeeze the tensor to remove dimensions of size 1
squeezed_tensor = torch.squeeze(tensor_with_extra_dim)
print("Squeezed tensor shape:", squeezed_tensor.shape)  # Output: torch.Size([3, 4])

# Squeeze a specific dimension (dimension 0 in this case)
squeezed_dim0 = torch.squeeze(tensor_with_extra_dim, dim=0)
print("Squeezed on dim 0 shape:", squeezed_dim0.shape)  # Output: torch.Size([3, 1, 4])

Original tensor shape: torch.Size([1, 3, 1, 4])
Squeezed tensor shape: torch.Size([3, 4])
Squeezed on dim 0 shape: torch.Size([3, 1, 4])


# Change the numpy array to torch

In [33]:
import numpy as np
a= np.array([[2,3],[3,4]])

torch.from_numpy(a)

tensor([[2, 3],
        [3, 4]])